ServiceHost/Areas/Administration/Pages/Accounts/Account/Index.cshtml.cs
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Account;

public class IndexModel : PageModel
{
    [TempData] public string Message { get; set; }

    public AccountSearchModel SearchModel;
    public List<AccountViewModel> Accounts;
    public SelectList Roles;

    private readonly IRoleApplication _roleApplication;
    private readonly IAccountApplication _accountApplication;

    public IndexModel(IAccountApplication accountApplication, IRoleApplication roleApplication)
    {
        _roleApplication = roleApplication;
        _accountApplication = accountApplication;
    }

    public void OnGet(AccountSearchModel searchModel)
    {
        Roles = new SelectList(_roleApplication.List(), "Id", "Name");
        Accounts = _accountApplication.Search(searchModel);
    }

    public IActionResult OnGetCreate()
    {
        var command = new RegisterAccount
        {
            Roles = _roleApplication.List()
        };
        return Partial("./Create", command);
    }

    public JsonResult OnPostCreate(RegisterAccount command)
    {
        var result = _accountApplication.Register(command);
        return new JsonResult(result);
    }

    public IActionResult OnGetEdit(long id)
    {
        var account = _accountApplication.GetDetails(id);
        account.Roles = _roleApplication.List();
        return Partial("Edit", account);
    }

    public JsonResult OnPostEdit(EditAccount command)
    {
        var result = _accountApplication.Edit(command);
        return new JsonResult(result);
    }

    public IActionResult OnGetChangePassword(long id)
    {
        var command = new ChangePassword {Id = id};
        return Partial("ChangePassword", command);
    }

    public JsonResult OnPostChangePassword(ChangePassword command)
    {
        var result = _accountApplication.ChangePassword(command);
        return new JsonResult(result);
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Role/Create.cshtml.cs
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class CreateModel : PageModel
    {
        public CreateRole Command;
        public List<SelectListItem> Permissions = new();

        private readonly IRoleApplication _roleApplication;

        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }


        public void OnGet()
        {
        }

        public IActionResult OnPost(CreateRole command)
        {
            var result = _roleApplication.Create(command);
            return RedirectToPage("./Index");
        }

    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Role/Edit.cshtml.cs
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class EditModel : PageModel
    {
        public EditRole Command;
        public List<SelectListItem> Permissions = new();

        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;

        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            _exposers = exposers;
            _roleApplication = roleApplication;
        }

        public void OnGet(long id)
        {
            Command = _roleApplication.GetDetails(id);

            var permissions = new List<PermissionDto>();
            foreach (var exposer in _exposers)
            {
                var exposedPermissions = exposer.Expose();
                foreach (var (key,value) in exposedPermissions)
                {
                    permissions.AddRange(value);
                    var group = new SelectListGroup
                    {
                        Name = key
                    };

                    foreach (var permission in value)
                    {
                        var item = new SelectListItem(permission.Name, permission.Code.ToString())
                        {
                            Group = group,
                        };

                        if (Command.MappedPermissions.Any(x => x.Code == permission.Code))
                            item.Selected = true;

                        Permissions.Add(item);
                    }
                }
            }
        }


        public IActionResult OnPost(EditRole command)
        {
            var result = _roleApplication.Edit(command);
            return RedirectToPage("./Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Role/Index.cshtml.cs
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role;

public class IndexModel : PageModel
{
    [TempData] public string Message { get; set; }
    public List<RoleViewModel> Roles;

    private readonly IRoleApplication _roleApplication;

    public IndexModel(IRoleApplication roleApplication)
    {
        _roleApplication = roleApplication;
    }

    public void OnGet()
    {
        Roles = _roleApplication.List();
    }

}

ServiceHost/Areas/Administration/Pages/Blog/ArticleCategories/Index.cshtml.cs
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductCategory;

namespace ServiceHost.Areas.Administration.Pages.Blog.ArticleCategories;

public class IndexModel : PageModel
{
    public ArticleCategorySearchModel SearchModel;
    public List<ArticleCategoryViewModel> ArticleCategories;

    private readonly IArticleCategoryApplication _articleCategoryApplication;

    public IndexModel(IArticleCategoryApplication articleCategoryApplication)
    {
        _articleCategoryApplication = articleCategoryApplication;
    }

    public void OnGet(ArticleCategorySearchModel searchModel)
    {
        ArticleCategories = _articleCategoryApplication.Search(searchModel);
    }

    public IActionResult OnGetCreate()
    {
        return Partial("./Create", new CreateArticleCategory());
    }

    public JsonResult OnPostCreate(CreateArticleCategory command)
    {
        var result = _articleCategoryApplication.Create(command);
        return new JsonResult(result);
    }

    public IActionResult OnGetEdit(long id)
    {
        var articleCategory = _articleCategoryApplication.GetDetails(id);
        return Partial("Edit", articleCategory);
    }

    public JsonResult OnPostEdit(EditArticleCategory command)
    {
        var result = _articleCategoryApplication.Edit(command);
        return new JsonResult(result);
    }
}

ServiceHost/Pages/AccessDenied.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ServiceHost/Pages/Account.cshtml.cs
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccountModel : PageModel
    {
        [TempData] public string LoginMessage { get; set; }
        [TempData] public string RegisterMessage { get; set; }

        private readonly IAccountApplication _accountApplication;

        public AccountModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }

        public void OnGet()
        {
            
        }

        public IActionResult OnPostLogin(Login command)
        {
            var result = _accountApplication.Login(command);

            if (result.IsSucceeded)
            {
                LoginMessage = result.Message;
                return RedirectToPage("/Index");
            }

            LoginMessage = result.Message;
            return RedirectToPage("/Account");
        }

        public IActionResult OnGetLogout()
        {
            _accountApplication.Logout();
            return RedirectToPage("/Index");
        }

        public IActionResult OnPostRegister(RegisterAccount command)
        {
            var result = _accountApplication.Register(command);

            if (result.IsSucceeded)
            {
                RegisterMessage = result.Message;
                return RedirectToPage("/Account");
            }

            RegisterMessage = result.Message;
            return RedirectToPage("/Account");
        }
    }
}

ServiceHost/Pages/Cart.cshtml.cs
using _01_LampshadeQuery.Contracts.Product;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Nancy.Json;
using ShopManagement.Application.Contracts.Order;

namespace ServiceHost.Pages
{
    public class CartModel : PageModel
    {
        public const string CookieName = "cart-items";
        public List<CartItem> CartItems;

        private readonly IProductQuery _productQuery;

        public CartModel(IProductQuery productQuery)
        {
            CartItems = new List<CartItem>();
            _productQuery = productQuery;
        }

        public void OnGet()
        {
            var serializer = new JavaScriptSerializer();
            var value = Request.Cookies[CookieName];

            if (value is null)
            {
                RedirectToPage("/Index");
                return;
            }

            var cartItems = serializer.Deserialize<List<CartItem>>(value);
            foreach (var item in cartItems)
                item.CalculateTotalItemPrice();

            CartItems = _productQuery.CheckInventoryStatus(cartItems);
        }

        public IActionResult OnGetRemoveFromCart(long id)
        {
            var serializer = new JavaScriptSerializer();
            var value = Request.Cookies[CookieName];
            Response.Cookies.Delete(CookieName);
            var cartItems = serializer.Deserialize<List<CartItem>>(value);
            var itemToRemove = cartItems.FirstOrDefault(x => x.Id == id);
            cartItems.Remove(itemToRemove);
            var options = new CookieOptions {Expires = DateTimeOffset.Now.AddDays(2)};
            var newCookie = serializer.Serialize(cartItems);
            Response.Cookies.Append(CookieName, newCookie);
            return RedirectToPage("/Cart");
        }

        public IActionResult OnGetGoToCheckOut()
        {
            var serializer = new JavaScriptSerializer();
            var value = Request.Cookies[CookieName];
            var cartItems = serializer.Deserialize<List<CartItem>>(value);
            foreach (var item in cartItems)
            {
                item.TotalItemPrice = item.UnitPrice * item.Count;
            }

            CartItems = _productQuery.CheckInventoryStatus(cartItems);

            /*if (CartItems.Any(x => !x.IsInStock))
                return RedirectToPage("/Cart");
            return RedirectToPage("/Checkout");*/

            return RedirectToPage(CartItems.Any(x => !x.IsInStock) ? "/Cart" : "/Checkout");
        }
    }
}

ServiceHost/Pages/Checkout.cshtml.cs
using System.Globalization;
using _0_Framework.Application;
using _0_Framework.Application.ZarinPal;
using _01_LampshadeQuery.Contracts;
using _01_LampshadeQuery.Contracts.Product;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Nancy.Json;
using ShopManagement.Application.Contracts.Order;

namespace ServiceHost.Pages;

[Authorize]
public class CheckoutModel : PageModel
{
    public Cart Cart;
    public const string CookieName = "cart-items";

    private readonly IAuthHelper _authHelper;
    private readonly ICartService _cartService;
    private readonly IProductQuery _productQuery;
    private readonly IZarinPalFactory _zarinPalFactory;
    private readonly IOrderApplication _orderApplication;
    private readonly ICartCalculatorService _cartCalculatorService;

    public CheckoutModel(ICartCalculatorService cartCalculatorService, ICartService cartService,
        IProductQuery productQuery, IOrderApplication orderApplication, IZarinPalFactory zarinPalFactory,
        IAuthHelper authHelper)
    {
        Cart = new();
        _authHelper = authHelper;
        _cartService = cartService;
        _productQuery = productQuery;
        _zarinPalFactory = zarinPalFactory;
        _orderApplication = orderApplication;
        _cartCalculatorService = cartCalculatorService;
    }

    public void OnGet()
    {
        var serializer = new JavaScriptSerializer();
        var value = Request.Cookies[CookieName];
        var cartItems = serializer.Deserialize<List<CartItem>>(value);
        foreach (var item in cartItems)
            item.CalculateTotalItemPrice();

        Cart = _cartCalculatorService.ComputeCart(cartItems);
        _cartService.Set(Cart);
    }

    public IActionResult OnPostPay(int paymentMethod)
    {
        var cart = _cartService.Get();
        cart.SetPaymentMethod(paymentMethod);

        var result = _productQuery.CheckInventoryStatus(cart.Items);
        if (result.Any(x => !x.IsInStock))
            return RedirectToPage("/Cart");

        var orderId = _orderApplication.PlaceOrder(cart);
        if (cart.PaymentMethod == 1)
        {
            var paymentResponse =
                _zarinPalFactory.CreatePaymentRequest(cart.PayAmount.ToString(CultureInfo.InvariantCulture), "", "",
                    "خرید از درگاه پرداخت تستی", orderId);

            return Redirect($"https://{_zarinPalFactory.Prefix}.zarinpal.com/pg/StartPay/{paymentResponse.Authority}");
        }
        else
        {
            var paymentResult = new PaymentResult();
            return RedirectToPage("/PaymentResult",
                paymentResult.Succeeded("سفارش شما با موفقیت ثبت شد و پس از تماس کارشناسان ما ارسال خواهد شد.", null));
        }
    }

    public IActionResult OnGetCallBack([FromQuery] string authority, [FromQuery] string status, [FromQuery] long oId)
    {
        var orderAmount = _orderApplication.GetAmountBy(oId);
        var verificationResponse = _zarinPalFactory.CreateVerificationRequest(authority, orderAmount.ToString(CultureInfo.InvariantCulture));

        var result = new PaymentResult();
        if (status == "OK" && verificationResponse.Status >= 100)
        {
            var issueTrackingNo = _orderApplication.PaymentSucceeded(oId, verificationResponse.RefID);
            Response.Cookies.Delete(CookieName);
            result = result.Succeeded("پرداخت با موفقیت انجام شد.", issueTrackingNo);
            return RedirectToPage("/PaymentResult", result);
        }
        else
        {
            result = result.Failed("پرداخت ناموفق بود.");
            return RedirectToPage("/PaymentResult", result);
        }
    }
}

ServiceHost/ViewComponents/LatestArrivalsViewComponent.cs
using _01_LampshadeQuery.Contracts.Product;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents;

public class LatestArrivalsViewComponent : ViewComponent
{
    private readonly IProductQuery _productQuery;

    public LatestArrivalsViewComponent(IProductQuery productQuery)
    {
        _productQuery = productQuery;
    }

    public IViewComponentResult Invoke()
    {
        var products = _productQuery.GetLatestArrivals();
        return View(products);
    }
}

ServiceHost/ViewComponents/LatestArticlesViewComponent.cs
using _01_LampshadeQuery.Contracts.Article;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents;

public class LatestArticlesViewComponent : ViewComponent
{
    private readonly IArticleQuery _articleQuery;

    public LatestArticlesViewComponent(IArticleQuery articleQuery)
    {
        _articleQuery = articleQuery;
    }

    public IViewComponentResult Invoke()
    {
        var articles = _articleQuery.LatestArticles();
        return View(articles);
    }
}

ServiceHost/ViewComponents/ProductCategoryViewComponent.cs
using _01_LampshadeQuery.Contracts.ProductCategory;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents;

public class ProductCategoryViewComponent : ViewComponent
{
    private readonly IProductCategoryQuery _productCategoryQuery;

    public ProductCategoryViewComponent(IProductCategoryQuery productCategoryQuery)
    {
        _productCategoryQuery = productCategoryQuery;
    }

    public IViewComponentResult Invoke()
    {
        var productCategory = _productCategoryQuery.GetProductCategories();
        return View(productCategory);
    }
}

ServiceHost/ViewComponents/SlideViewComponent.cs
using _01_LampshadeQuery.Contracts.Slide;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents;

public class SlideViewComponent : ViewComponent
{
    private readonly ISlideQuery _slideQuery;

    public SlideViewComponent(ISlideQuery slideQuery)
    {
        _slideQuery = slideQuery;
    }

    public IViewComponentResult Invoke()
    {
        var slider = _slideQuery.GetSlides();
        return View(slider);
    }
}

ServiceHost/Pages/AccessDenied.cshtml
@page
@model ServiceHost.Pages.AccessDeniedModel
@{
}

<div class="wrapper-page">
    <div class="ex-page-content text-center">
        <h1>404!</h1>
        <h2>Sorry, page not found</h2><br>
        <a class="btn btn-purple waves-effect waves-light" asp-page="/Index"><i class="fa fa-angle-left"></i> بازگشت به صفحه اصلی</a>
    </div>
</div>

ServiceHost/Pages/Account.cshtml
@page
@model ServiceHost.Pages.AccountModel
@{
    ViewData["Title"] = "ورود و ثبت نام";
}


<div class="breadcrumb-area section-space--half">
    <div class="container wide">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-wrapper breadcrumb-bg">
                    <div class="breadcrumb-content">
                        <h2 class="breadcrumb-content__title">ورود و ثبت نام</h2>
                        <ul class="breadcrumb-content__page-map">
                            <li><a asp-page="/Index">صفحه اصلی</a></li>
                            <li class="active">ورود - ثبت نام</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-wrapper">
                    <div class="page-content-wrapper">
                        <div class="row">
                                @*@if (Model.LoginMessage is not null)
                                {
                                    <div class="alert alert-danger">@Model.LoginMessage</div>
                                }*@
                            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6">
                                <form method="post" asp-page-handler="Login">
                                    <div class="login-form">
                                        <h4 class="login-title">ورود</h4>
                                        <div class="row">
                                            <div class="col-md-12 col-12">
                                                <label>نام کاربری</label>
                                                <input type="text" name="username" placeholder="نام کاربری">
                                            </div>
                                            <div class="col-12">
                                                <label>رمز</label>
                                                <input type="password" name="password" placeholder="رمز">
                                            </div>

                                            @*<div class="col-sm-6">
                                                <div class="check-box d-inline-block ml-0 ml-md-2">
                                                    <input type="checkbox" id="remember_me">
                                                    <label for="remember_me">Remember me</label>
                                                </div>
                                            </div>*@

                                            <div class="col-sm-6 text-left text-sm-right">
                                                <a href="#" class="forget-pass-link"> رمز را فراموش کرده اید؟</a>
                                            </div>

                                            <div class="col-md-12">
                                                <button class="register-button">ورود</button>
                                            </div>

                                        </div>
                                    </div>

                                </form>
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-6 col-xs-12">
                                @if (Model.RegisterMessage is not null)
                                {
                                    <div class="alert alert-danger">@Model.RegisterMessage</div>
                                }
                                <form method="post" asp-page-handler="Register">
                                    <div class="login-form">
                                        <h4 class="login-title">ثبت نام</h4>

                                        <div class="row">
                                            <div class="col-md-6 col-12 mb-20">
                                                <label>نام کامل</label>
                                                <input type="text" name="fullname" placeholder="نام کامل">
                                            </div>
                                            <div class="col-md-6 col-12 mb-20">
                                                <label>نام کاربری</label>
                                                <input type="text" name="username" placeholder="نام کاربری">
                                            </div>
                                            <div class="col-md-12 mb-20">
                                                <label>موبایل</label>
                                                <input type="tel" name="mobile" placeholder="موبایل">
                                            </div>
                                            <div class="col-md-6 mb-20">
                                                <label>رمز</label>
                                                <input type="password" name="password" placeholder="رمز">
                                            </div>
                                            <div class="col-md-6 mb-20">
                                                <label>تایید رمز</label>
                                                <input type="password" name="rePassword" placeholder="تایید رمز">
                                            </div>
                                            <div class="col-12">
                                                <button class="register-button mt-0">ثبت نام</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ServiceHost/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "صفحه اصلی";
}

@await Component.InvokeAsync("Slide")

@await Component.InvokeAsync("ProductCategory")

@await Component.InvokeAsync("ProductCategoryWithProduct")

@await Component.InvokeAsync("LatestArrivals")


<div class="banner-hover-area section-space">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="banner-hover-wrapper">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="single-hover-banner">
                                <div class="single-hover-banner__image">
                                    <a href="shop-left-sidebar.html">
                                        <img src="~/Theme/assets/img/banners/img1-middle-eposi1.jpg" class="img-fluid"
                                             alt="">
                                    </a>
                                    <div class="single-hover-banner__content">
                                        <h4 class="small-text">شگفت انگیزها</h4>
                                        <h3 class="big-text">تا 50% تخفیف</h3>
                                        <a class="banner-link" href="shop-left-sidebar.html">خرید کنید</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="single-hover-banner">
                                <div class="single-hover-banner__image">
                                    <a href="shop-left-sidebar.html">
                                        <img src="~/Theme/assets/img/banners/img2-middle-eposi1.jpg" class="img-fluid"
                                             alt="">
                                    </a>
                                    <div class="single-hover-banner__content">
                                        <h4 class="small-text">پرطرفدار ترین محصولات</h4>
                                        <h3 class="big-text">با اطمینان بخرید</h3>
                                        <a class="banner-link" href="shop-left-sidebar.html">محصولات بیشتر</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="feature-logo-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="feature-logo-wrapper section-space--inner-bottom">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="single-feature-logo">
                                <div class="single-feature-logo__image">
                                    <img src="~/Theme/assets/img/icons/free_shipping.png" class="img-fluid" alt="">
                                </div>
                                <div class="single-feature-logo__content">
                                    <h4 class="title">ارسال رایگان</h4>
                                    <p class="short-desc">
                                        ارسال رایگان به سراسر ایران برای سفارش های بالای 500 هزار تومان
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="single-feature-logo">
                                <div class="single-feature-logo__image">
                                    <img src="~/Theme/assets/img/icons/money_back.png" class="img-fluid" alt="">
                                </div>
                                <div class="single-feature-logo__content">
                                    <h4 class="title">گارانتی بازگشت وجه</h4>
                                    <p class="short-desc">
                                        اگر از محصول دریافتی راضی نیستید، مبلغ پرداختی به طور کامل به شما بازگردانده خواهد شد.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="single-feature-logo">
                                <div class="single-feature-logo__image">
                                    <img src="~/Theme/assets/img/icons/support247.png" class="img-fluid" alt="">
                                </div>
                                <div class="single-feature-logo__content">
                                    <h4 class="title">پشتیبانی آنلاین 24/7</h4>
                                    <p class="short-desc">
                                        تیم پشتیبانی ما برای خدمت رسانی 24 ساعته در 7 روز هفته آماده است.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@await Component.InvokeAsync("LatestArticles")


<div class="newsletter-area section-space--inner">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 offset-lg-2">
                <div class="newsletter-wrapper">
                    <p class="small-text">پیشنهادات ویژه برای مشترکان</p>
                    <h3 class="title">ده درصد تخفیف اعضا</h3>
                    <p class="short-desc">
                        عضو خبرنامه شوید تا از آخرین تخفیفات زودتر از سایرین مطلع شوید.
                    </p>

                    <div class="newsletter-form">
                        <form id="mc-form" class="mc-form">
                            <input type="email" placeholder="آدرس ایمیل خود را وارد کنید..." required>
                            <button type="submit" value="submit">عضویت</button>
                        </form>

                    </div>
                    <div class="mailchimp-alerts">
                        <div class="mailchimp-submitting"></div>
                        <div class="mailchimp-success"></div>
                        <div class="mailchimp-error"></div> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>